# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xa6\x01\n\tMyService\x12\x19\n\x03\x41\x64\x64\x12\x07.addMsg\x1a\t.addReply\x12%\n\x08RawImage\x12\x0c.rawImageMsg\x1a\x0b.imageReply\x12.\n\nDotProduct\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\x12\'\n\tJsonImage\x12\r.jsonImageMsg\x1a\x0b.imageReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDMSG._serialized_start=17
  _ADDMSG._serialized_end=47
  _RAWIMAGEMSG._serialized_start=49
  _RAWIMAGEMSG._serialized_end=75
  _DOTPRODUCTMSG._serialized_start=77
  _DOTPRODUCTMSG._serialized_end=114
  _JSONIMAGEMSG._serialized_start=116
  _JSONIMAGEMSG._serialized_end=143
  _ADDREPLY._serialized_start=145
  _ADDREPLY._serialized_end=168
  _DOTPRODUCTREPLY._serialized_start=170
  _DOTPRODUCTREPLY._serialized_end=207
  _IMAGEREPLY._serialized_start=209
  _IMAGEREPLY._serialized_end=252
  _MYSERVICE._serialized_start=255
  _MYSERVICE._serialized_end=421
# @@protoc_insertion_point(module_scope)
